<input id="measure-unit" name="unit" value="0" type="hidden"/>
<input id="measure-drop" name="drop" value="" type="hidden"/>
<input id="measure-dropodd" name="drop_odd" value="0" type="hidden"/>
<input id="measure-width" name="width" type="hidden" value=""/>
<input id="measure-widthodd" name="width_odd" type="hidden" value="0"/>
<input type="hidden" id="price_matrix" name="price_matrix" value=""/>
<input name="productId" type="hidden" id="prd_id" value="<?php echo $this->getCurrentProductId(); ?>">
